"""empty message

Revision ID: 761b31f9471b
Revises: 
Create Date: 2022-09-02 13:12:41.764056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761b31f9471b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('name', 'description')
    )
    op.create_table('users',
    sa.Column('first_name', sa.String(length=300), nullable=False),
    sa.Column('last_name', sa.String(length=300), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('first_name', 'last_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
