"""empty message

Revision ID: a91973418df9
Revises: 761b31f9471b
Create Date: 2022-09-02 13:29:33.886338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91973418df9'
down_revision = '761b31f9471b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_name', sa.String(length=300), nullable=False))
    op.drop_column('products', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_column('products', 'product_name')
    # ### end Alembic commands ###
